# Simple configuration for an HTTP proxy listening on port 80 on all
# interfaces and forwarding requests to a single backend "servers" with a
# single server "server1" listening on 127.0.0.1:8000
global
    daemon
    maxconn 1000

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:9999
    default_backend servers

backend servers
    server server1 127.0.0.1:10000 maxconn 400
    server server2 127.0.0.1:10001 maxconn 400
